### ISSUE TITLE
Is it possible to choose alpha such that the integrated likelihood of the combined prior is bigger than the maximum integrated likelihood of the original priors?

### ISSUE THREAD

**Issue by maxbiostat** [maxbiostat/opinion_pooling#10]
Would be interesting to prove the result in general.

**Comment by lsbastos** [comment]
Opa,

Vou dar uma olhada nisso terça feira.

Abraço,
Leo
Em 13/06/2015 15:53, "Luiz Max F. Carvalho" <notifications@github.com>
escreveu:

**Comment by maxbiostat** [comment]
Answer is yes. Maybe in the future someone could look into how to choose $\alpha$ in such a way as to maximise the marginal likelihood.
