### ISSUE TITLE
equation (31) is wrong

### ISSUE THREAD

**Issue by maxbiostat** [maxbiostat/opinion_pooling#11]
there's a minus sign that shouldn't be there. 

Re-do the calcs

**Comment by lsbastos** [comment]
Yeup,

The correct one:

#################
Thus
\begin{align}
\pi(\mu)&= t(\boldsymbol\alpha)\prod_{i=0}^{K}f_i(\mu; m_i,
v_i)^{\alpha_i}\\
 &\propto \prod_{i=0}^{K} \left[ \exp \left(-\frac{(\mu-m_i)^2}{2v_i}
\right) \right]^{\alpha_i} \\
&\propto \exp\left[-\frac{1}{2}\left\{\mu^2
\sum_{i=0}^K\frac{\alpha_i}{v_i} - 2 \mu \sum_{i=0}^K \frac{\alpha_i
m_i}{v_i} \right\} \right] % \\
 %&\propto \exp \left( -\frac{1}{2}\frac{(\mu-m^*)^2}{v^*} \right)
\end{align}
which yields a normal distribution with parameters and $m^* =
\frac{\sum_{i=0}^K w_i m_i}{\sum_{i=0}^K w_i}$ and $v^* = [\sum_{i=0}^K
w_i]^{-1}$,  where $w_i = \alpha_i/v_i$.
################

- Fiz as correções nas equacoes (29-31)
- Mudei a variancia s_i^2  para v_i, só para tirar o "^2".
- Vc me explicou, mas eu me esqueci como usar o github. Um dia eu aprendo.
:-)



_______________________________________________________@_'-'
Leonardo S. Bastos, PhD
Researcher at Scientific Computing Program (PROCC)
Oswaldo Cruz Foundation - Fiocruz
Homepage: http://www.procc.fiocruz.br/Members/lsbastos
CV Lattes: http://lattes.cnpq.br/5241799121437269
Phone: +55 21 3836 1112 (office)
Alternative emails: lsbastos.fiocruz@gmail.com; lsbastos@pq.cnpq.br

2015-08-26 14:04 GMT-03:00 Luiz Max F. Carvalho <notifications@github.com>:
