### ISSUE TITLE
dynamic model example

### ISSUE THREAD

**Issue by maxbiostat** [maxbiostat/opinion_pooling#14]
@fccoelho , @lsbastos and @DVMath :

I propose to use the model in [Carvalho, Bastos & Struchiner (2015)](https://github.com/maxbiostat/papers/blob/master/CHAPTERS/Carvalho_Struchiner_Bastos_2015_Chap18_unrevised_preprint.pdf)

It has three levels:
- 0. The hyperparameters of the thermodynamic functions;
- 1. The thermodynamic functions r(T) and K(T);
- 2. The population size P(t, T)

Problems:
Figure out a sensible propagation strategy: it probably doesn't make any sense to propagate the uncertainty on the hyperparameters caused by uncertainty on P(t,T), although it is certainly desirable to study how the uncertainty about the hyperparameters influences the uncertainty on P(t,T).

An initial idea, thus, is to study only the prior on P(t,T) obtained by combining:

Induced prior on P(t,T) from the hyperparameters + induced prior on P(t,T) from the priors on the functions r(T) and K(T) and the actual prior on P(t,T).
This would be nice because we would be combining uncertainty from three levels and also because we could in principle apply our automatic methods to choose the weights (alpha). 

As a bonus, we could look into the combined prior for r(T) and K(T) combining only:
(i) the induced priors from the hyperparameters and (ii) the actual priors on r(T) and K(T).

**Comment by fccoelho** [comment]
@maxbiostat, your paper is behind a paywall!! so I can't say anything about
it.

The strategy seems sound. When you can, send me a reprint so that I can
come up with more specific comments.


On Tue, Sep 1, 2015 at 1:48 PM, Luiz Max F. Carvalho <
notifications@github.com> wrote:

> @fccoelho <https://github.com/fccoelho> , @lsbastos
> <https://github.com/lsbastos> and @DVMath <https://github.com/DVMath> :
>
> I propose to use the model in Carvalho, Bastos & Struchiner (2015)
> <http://download.springer.com/static/pdf/361/chp%253A10.1007%252F978-3-319-12454-4_18.pdf?originUrl=http%3A%2F%2Flink.springer.com%2Fchapter%2F10.1007%2F978-3-319-12454-4_18&token2=exp=1441126335%7Eacl=%2Fstatic%2Fpdf%2F361%2Fchp%25253A10.1007%25252F978-3-319-12454-4_18.pdf%3ForiginUrl%3Dhttp%253A%252F%252Flink.springer.com%252Fchapter%252F10.1007%252F978-3-319-12454-4_18*%7Ehmac=e342b03f4d5796c4ad352cf932a5a2c5d7cd5e8ed026f097ca6bfe79948f3027>
>
> It has three levels:
>
>    - 0. The hyperparameters of the thermodynamic functions;
>    - 1. The thermodynamic functions r(T) and K(T);
>    - 2. The population size P(t, T)
>
> Problems:
> Figure out a sensible propagation strategy: it probably doesn't make any
> sense to propagate the uncertainty on the hyperparameters caused by
> uncertainty on P(t,T), although it is certainly desirable to study how the
> uncertainty about the hyperparameters influences the uncertainty on P(t,T).
>
> An initial idea, thus, is to study only the prior on P(t,T) obtained by
> combining:
>
> Induced prior on P(t,T) from the hyperparameters + induced prior on P(t,T)
> from the priors on the functions r(T) and K(T) and the actual prior on
> P(t,T).
> This would be nice because we would be combining uncertainty from three
> levels and also because we could in principle apply our automatic methods
> to choose the weights (alpha).
>
> As a bonus, we could look into the combined prior for r(T) and K(T)
> combining only:
> the induced priors from the hyperparameters and the actual priors on r(T)
> and K(T).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maxbiostat/opinion_pooling/issues/14>.
>



-- 
Flávio Codeço Coelho
================
+55(21) 3799-5551
Professor
Escola de Matemática Aplicada
Fundação Getulio Vargas
Praia de Botafogo, 190 sala 312
Rio de Janeiro - RJ
22250-900
Brasil

**Comment by maxbiostat** [comment]
@fccoelho check it now.

**Comment by maxbiostat** [comment]
Closing for the time being. Model is really very complex and would be a nice test case. But we have enough on our plates as is.
