### ISSUE TITLE
ask Raftery about transformation stuff

### ISSUE THREAD

**Issue by maxbiostat** [maxbiostat/opinion_pooling#29]
In EBEB 2016 Mike West said he didn't find the fact that LP is invariant under symmetric transforms (and *not* invariant under non-invertible transforms) very interesting. 

I'm not sure.

Can ask Raftery.

@fccoelho @lsbastos @DVMath , your 2 cents?

**Comment by fccoelho** [comment]
Looked in the manuscript and found no mention to it. Why exactly do we care about it? I get that in the case of the Melding, the model may be a non-invertible transformation, but...

**Comment by maxbiostat** [comment]
This has now moved on a bit. [These](https://github.com/maxbiostat/opinion_pooling/blob/master/notes/order_of_operations_log_pooling.pdf) notes will eventually lead to a short paper discussing the role of transformations in pooling.
