### ISSUE TITLE
Should we generalise the examples of Beta & Gamma to the exponential family?

### ISSUE THREAD

**Issue by maxbiostat** [maxbiostat/opinion_pooling#4]
In their BA paper, Rufo et al. (2012) derive their results for the exponential family. Should we follow them and derive [the properties of] our hierarchical prior for the expo family too? @lsbastos & @fccoelho ?

**Comment by fccoelho** [comment]
That would be a desirable goal for a full paper, in my opinion. For this, it would suffice to keep the  examples and discuss real world applicability. I think we should also add some visual representation of the examples for more impact.

**Comment by lsbastos** [comment]
I agree with Flavio. The results for exponential family would be nice for a full paper.

**Comment by maxbiostat** [comment]
Done by @lsbastos
