### ISSUE TITLE
How to compare the priors?

### ISSUE THREAD

**Issue by maxbiostat** [maxbiostat/opinion_pooling#5]
Professor Raftery suggested using integrated likelihoods. Problem is: once we calculate them, what are going to do with them? Calculate prior odds?

Mrs @lsbastos and @fccoelho, o poder e' de voces!

Ass. Capitao Planeta

**Comment by maxbiostat** [comment]
Amiguinho @DVMath is in.

Ass. CP

**Comment by fccoelho** [comment]
Possible interesting reference: http://projecteuclid.org/euclid.ss/1009211804 but I have no time to study it. Prior odds or posterior odds seem to be more intuitive to me

**Comment by maxbiostat** [comment]
We ended up using integrated likelihoods, which, I think, helped shed some light on the results
