### ISSUE TITLE
proofreading

### ISSUE THREAD

**Issue by maxbiostat** [maxbiostat/opinion_pooling#7]

**Comment by fccoelho** [comment]
@maxbiostat please increase the font sizes in the figure.

**Comment by maxbiostat** [comment]
@fccoelho @DVMath please see if the figure is good-to-go now.

**Comment by DVMath** [comment]
I know that you increased font sizes, but now they could be a bit smaller,
but this is a minor issue.

--
Daniel A. M. Villela

**Comment by DVMath** [comment]
do you use cex (for the fonts) in the R code?

--
Daniel A. M. Villela

**Comment by maxbiostat** [comment]
Nope. Code is now available at the repo

**Comment by DVMath** [comment]
noticed two missing references, but you are probably working on it: reference to stan (?) and likelihood (?, eq. 9) on page 4.  I think it is ready.  Nice job!

**Comment by maxbiostat** [comment]
Thanks. Gonna submit soon. Wanna go through it before I do it?

On 13 February 2015 at 21:50, DVMath <notifications@github.com> wrote:

> noticed two missing references, but you are probably working on it:
> reference to stan (?) and likelihood (?, eq. 9) on page 4. I think it is
> ready. Nice job!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maxbiostat/opinion_pooling/issues/7#issuecomment-74333227>
> .
>



-- 
Luiz Max Fagundes de Carvalho
PhD student, Institute of Evolutionary Biology,  School of Biological
Sciences,
Ashworth Laboratories, Ash 2, office 123
University of Edinburgh, United Kingdom.
http://br.linkedin.com/pub/luiz-max-carvalho/49/687/283

**Comment by DVMath** [comment]
You can go ahead!

--
Daniel A. M. Villela

**Comment by maxbiostat** [comment]
Roger that.

On 13 February 2015 at 21:57, DVMath <notifications@github.com> wrote:

> You can go ahead!
>
> --
> Daniel A. M. Villela
>
> On Fri, Feb 13, 2015 at 7:53 PM, Luiz Max F. Carvalho <
> notifications@github.com> wrote:
>
> > Thanks. Gonna submit soon. Wanna go through it before I do it?
> >
> > On 13 February 2015 at 21:50, DVMath <notifications@github.com> wrote:
> >
> > > noticed two missing references, but you are probably working on it:
> > > reference to stan (?) and likelihood (?, eq. 9) on page 4. I think it
> is
> > > ready. Nice job!
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/maxbiostat/opinion_pooling/issues/7#issuecomment-74333227
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Luiz Max Fagundes de Carvalho
> > PhD student, Institute of Evolutionary Biology, School of Biological
> > Sciences,
> > Ashworth Laboratories, Ash 2, office 123
> > University of Edinburgh, United Kingdom.
> > http://br.linkedin.com/pub/luiz-max-carvalho/49/687/283
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/maxbiostat/opinion_pooling/issues/7#issuecomment-74333645
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maxbiostat/opinion_pooling/issues/7#issuecomment-74334267>
> .
>



-- 
Luiz Max Fagundes de Carvalho
PhD student, Institute of Evolutionary Biology,  School of Biological
Sciences,
Ashworth Laboratories, Ash 2, office 123
University of Edinburgh, United Kingdom.
http://br.linkedin.com/pub/luiz-max-carvalho/49/687/283
